// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bwDhwFUETyqIWlT4xkJiKwSCF8DzNGE',
    appId: '1:796938949800:web:201f73c044e6f7fb56de9d',
    messagingSenderId: '796938949800',
    projectId: 'applier-29b7e',
    authDomain: 'applier-29b7e.firebaseapp.com',
    storageBucket: 'applier-29b7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0aVFtfxjnPUTncHjMat1kgN8FOINyn0',
    appId: '1:796938949800:android:d4a4832a50eb0fa956de9d',
    messagingSenderId: '796938949800',
    projectId: 'applier-29b7e',
    storageBucket: 'applier-29b7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xeVzWMH1pRmImw1u3woNlcODQhDBx7U',
    appId: '1:796938949800:ios:d997b2f2e56cb27856de9d',
    messagingSenderId: '796938949800',
    projectId: 'applier-29b7e',
    storageBucket: 'applier-29b7e.appspot.com',
    iosClientId:
        '796938949800-jpf1q91hg1e13aid3s140v1mrnaigto2.apps.googleusercontent.com',
    iosBundleId: 'com.example.applierapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2xeVzWMH1pRmImw1u3woNlcODQhDBx7U',
    appId: '1:796938949800:ios:d997b2f2e56cb27856de9d',
    messagingSenderId: '796938949800',
    projectId: 'applier-29b7e',
    storageBucket: 'applier-29b7e.appspot.com',
    iosClientId:
        '796938949800-jpf1q91hg1e13aid3s140v1mrnaigto2.apps.googleusercontent.com',
    iosBundleId: 'com.example.applierapp',
  );
}
